<?php 

$listExample = [
    [
        /** Module Name 
         * use PascalCase to define module name, letter char tobe replacing with uderscore if you use 2 words like "UserSession = user_session"
        */
        "name" => "Users", // use PascalCase to define module name, letter tobe replacing with uderscore if you use 2 words li
        "loging_date" => true, // to activate created_at & updated_at including soft delete of table.
        "column" => [
            [
                "type" => "enum",  "name" => "id", 
                "length" => 18, 
                "length2" => 3, 
                "default" => "0", 
                "attributes" => ['index','nullable'], 
                "fulltext" => true,
                "enum_list" => "['open', 'closed', 'expired']"
            ],
        ],
    ]
];

$list = [
    /** DEFAULT MODULE
     * Be careful about changing / deleting the user & userSessions module, 
     * because this module is the default module for setting up authentication, 
     * unless you already understand or don't need it and are aware of the risks.
     * Users         : module to manage data user of application
     * UserSession     : module to manage all session of user logged in
    */ 
 
    ["name" => "Users",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "name",
                "type" => "string", 
            ],
            [ "name" => "username",
                "type" => "string", 
            ],
            [ "name" => "password",
                "type" => "string", 
            ],
            [ "name" => "email",
                "type" => "string", 
            ],
            [ "name" => "picture",
                "type" => "text", 
                "attributes" => ['nullable'], 
            ],
            [ "name" => "role_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "menu_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "active",
                "type" => "tinyInteger", 
                "default" => 0, 
            ],
            
        ],
    ],

    ["name" => "UserSessions",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "user_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            [ "name" => "token",
                "type" => "text", 
            ],
            [ "name" => "ip",
                "type" => "string", 
                "attributes" => ['nullable'], 
            ],
            [ "name" => "agent",
                "type" => "string", 
                "attributes" => ['nullable'], 
            ],
            [ "name" => "platform",
                "type" => "string", 
                "attributes" => ['nullable'], 
            ],
            
        ],
    ],

    ["name" => "Permissions",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string", 
            ],
            [ "name" => "slug",
                "type" => "string", 
                "attributes" => ['nullable'], 
            ],
            
        ],
    ],

    ["name" => "RolePermissions",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "permission_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            [ "name" => "role_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            
        ],
    ],

    ["name" => "Roles",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string", 
            ],
            [ "name" => "slug",
                "type" => "string", 
                "attributes" => ['nullable'], 
            ],
            
        ],
    ],

    ["name" => "MenuItems",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "slug",
                "type" => "string",
                "attributes" => ['index'],
            ],
            [ "name" => "icon",
                "type" => "text",
                "attributes" => ['nullable'],
            ],
            [ "name" => "path",
                "type" => "text",
                "attributes" => ['nullable'],
            ],
            
        ],
    ],

    ["name" => "Menus",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "parent_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index', 'nullable'],
            ],
            [ "name" => "menu_item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            [ "name" => "master_menu_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            [ "name" => "overline",
                "type" => "string",
                "attributes" => ['nullable'],
            ],
            [ "name" => "ordering",
                "type" => "integer", 
                "default" => "0",
            ],
            
        ],
    ],

    ["name" => "MasterMenus",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            
        ],
    ],

    ["name" => "UserNotifications",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "user_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            [ "name" => "is_read",
                "type" => "boolean",
                "default" => "false",
            ],
            [ "name" => "title",
                "type" => "string", 
                "attributes" => ['nullable'],
                "fulltext" => true, 
            ],
            [ "name" => "description",
                "type" => "text", 
                "attributes" => ['nullable'],
                "fulltext" => true, 
            ],
            [ "name" => "type",
                "type" => "string", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "link_path",
                "type" => "string", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "link_params",
                "type" => "json", 
                "attributes" => ['nullable'],
            ],
            
        ],
    ],

    // modules

    ["name" => "Projects",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "code",
                "type" => "string", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "name",
                "type" => "string",
                "attributes" => ['nullable'],
            ],
            [ "name" => "start_date",
                "type" => "dateTime", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "end_date",
                "type" => "dateTime", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "actual_start_date",
                "type" => "dateTime", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "actual_end_date",
                "type" => "dateTime", 
                "attributes" => ['nullable'],
            ],
            
        ],
    ],

    ["name" => "ProjectConfig",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "project_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string", 
                "attributes" => ['index'],
            ],
            [ "name" => "value",
                "type" => "string", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "description",
                "type" => "string", 
                "attributes" => ['nullable'],
            ],
        ],
    ],

    ["name" => "ProjectMembers",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "project_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "user_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            
        ],
    ],


    ["name" => "Works",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "project_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "related",
                "type" => "json", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "name",
                "type" => "string",
                "attributes" => ['nullable'],
            ],
            [ "name" => "summary",
                "type" => "text",
                "attributes" => ['nullable'],
            ],
            [ "name" => "description",
                "type" => "longtext",
                "attributes" => ['nullable'],
            ],
            [ "name" => "priority",
                "type"      => "enum",
                "default"   => "'REGULAR'",
                "enum_list" => "['REGULAR', 'LOW', 'HIGH', 'URGENT']",
            ],
            [ "name" => "status",
                "type"      => "enum",
                "default"   => "'OPEN'",
                "enum_list" => "['OPEN', 'RUNNING', 'COMPLETED']",
            ],
            [ "name" => "labels", // foreign : WorkLabels
                "type" => "json",
                "attributes" => ['nullable'],
            ],
            [ "name" => "is_module",
                "type"      => "tinyInteger",
                "default"   => 0,
            ],
        ],
    ],

    ["name" => "WorkLabels",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string", 
                "attributes" => ['index'],
            ],
            [ "name" => "project_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "color",
                "type" => "string", 
                "attributes" => ['nullable'],
            ],
            
        ],
    ],

    ["name" => "WorkAssignees",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "work_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "user_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            
        ],
    ],

    ["name" => "Sprints",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "project_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "work_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index', 'nullable'],
            ],
            [ "name" => "name",
                "type" => "string", 
                "attributes" => ['index'],
            ],
            [ "name" => "goals",
                "type" => "longtext", 
                "attributes" => ['index', 'nullable'],
            ],
            [ "name" => "status",
                "type"      => "enum",
                "default"   => "'OPEN'",
                "enum_list" => "['OPEN', 'STARTED', 'FINISHED']",
            ],
            [ "name" => "start_date",
                "type" => "dateTime", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "end_date",
                "type" => "dateTime", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "actual_start_date",
                "type" => "dateTime", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "actual_end_date",
                "type" => "dateTime", 
                "attributes" => ['nullable'],
            ],
            
        ],
    ],

    ["name" => "Tasks",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "project_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index', 'nullable'],
            ],
            [ "name" => "sprint_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index', 'nullable'],
            ],
            [ "name" => "work_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "status", // foreign : TaskStatus
                "type" => "unsignedBigInteger", 
                "attributes" => ['index', 'nullable'],
            ],
            [ "name" => "name",
                "type" => "string", 
                "attributes" => ['index'],
            ],
            [ "name" => "description",
                "type" => "longtext", 
                "attributes" => ['index', 'nullable'],
            ],
            [ "name" => "start_date",
                "type" => "dateTime", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "end_date",
                "type" => "dateTime", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "actual_start_date",
                "type" => "dateTime", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "actual_end_date",
                "type" => "dateTime", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "labels", // foreign : TaskLabels
                "type" => "json",
                "attributes" => ['nullable'],
            ],
            [ "name" => "ordering",
                "type" => "integer", 
                "default" => 1,
            ],
            [ "name" => "mandays",
                "type" => "double",
                "attributes" => ['nullable'],
                "length" => 18, 
                "length2" => 2,
                "default" => 0,
            ],
            [ "name" => "mandays_actual",
                "type" => "double",
                "attributes" => ['nullable'],
                "length" => 18, 
                "length2" => 2,
                "default" => 0,
            ],
            [ "name" => "is_overtime", // foreign : TaskLabels
                "type" => "tinyInteger",
                "default" => 0,
            ],
            [ "name" => "is_done", // foreign : TaskLabels
                "type" => "tinyInteger",
                "default" => 0,
            ],
            
        ],
    ],

    ["name" => "TaskComments",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "task_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "description",
                "type" => "longtext", 
            ],
            [ "name" => "reply",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index', 'nullable'],
            ],
            
        ],
    ],

    ["name" => "TaskComponents", // untuk menyimpan, scheme sql, rules, catatan tambahan, dll
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "project_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index', 'nullable'],
            ],
            [ "name" => "task_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string", 
            ],
            [ "name" => "summary",
                "type" => "text",
                "attributes" => ['nullable'],
            ],
            [ "name" => "description",
                "type" => "longtext", 
            ],
            [ "name" => "type",
                "type"      => "enum",
                "default"   => "'DOC'",
                "enum_list" => "['DOC', 'DOC-API', 'SQL', 'RULE', 'NOTE', 'OTHER']",
            ],
            
        ],
    ],

    ["name" => "TaskStatus", // otomatis create : TO DO, PROGRESS, REVIEW, DONE
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "project_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string", 
                "attributes" => ['index'],
            ],
            
        ],
    ],

    ["name" => "TaskLabels",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "project_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string", 
                "attributes" => ['index'],
            ],
            [ "name" => "color",
                "type" => "string", 
                "attributes" => ['nullable'],
            ],
        ],
    ],

    ["name" => "TaskAssignees",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "task_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "user_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            
        ],
    ],
    
    
];
